### ISSUE TITLE
Facing syntax errors in plsql while creating views with safeViewDefinition.

### ISSUE THREAD

**Issue by avinashkurup** [netspective-labs/sql-aide#13]
Hi,
    The output .sql file has the view generated as follows,

```sql
CREATE VIEW IF NOT EXISTS "view_name"() AS
    
    SELECT 
     ...
;
```

I used the following typescript code to generate this,

```typescript
const viewObj = view.safeViewDefinition("view_name", {}, {
  isIdempotent: true, embeddedStsOptions: SQLa.typicalSqlTextSupplierOptions()
})`
 // View select code goes here
```

I face the following psql error when running the output sql file, 

```
ERROR:  42601: syntax error at or near "NOT"
LINE 1: CREATE VIEW IF NOT EXISTS "view_name"() AS
```
Please note, In SQLite the idempotent view management 'IF NOT EXISTS' is correct,
however In PostgreSQL it should be 'CREATE OR REPLACE VIEW'.

Regards,
Avinash.

**Comment by shah** [comment]
The `CREATE OR REPLACE VIEW` fix has been added but `view.safeViewDefinition("view_name", {})` is not a bug. If you want to use `safeViewDefinition` you must pass in a proper shape. If you don't want to use anything in the view just use `view.viewDefinition` (not `safeViewDefinition`).
