### ISSUE TITLE
Expose column and columnList on viewDefinition

### ISSUE THREAD

**Issue by geovlazar** [netspective-labs/sql-aide#132]
Need to pass viewDefinition in `lib/osquery/atc_test.ts`  test case osQueryATCConfigSupplier with auto-generated queries. When we try to do that we get Type error ` Property 'columnsList' does not exist on type 'ViewDefinition<string, SqlEmitContext>'` 

For that we need to expose column and columnList on viewDefinition.

**Comment by shah** [comment]
Exposed `domains` in `render/ddl/view.ts` `ViewDefintion` the same at is in in `TableDefinition`.
