### ISSUE TITLE
Add Constraint to MSSQL Create table Script

### ISSUE THREAD

**Issue by razakpm** [netspective-labs/sql-aide#17]
We need to add constraints in MSSQL to achieve the Primary key, foreign key  etc.. with Create table script and autoIncPkTable.

A sample MS SQL script we need is 

```
CREATE TABLE[job_position](
[job_position_id] integer IDENTITY (1, 1) NOT NULL,
[position_title] text NOT NULL,
[job_category_id] integer NOT NULL,
[description] text,
[requirements] text,
[responsibilities] text,
[department_id] integer NOT NULL,
[grade_id] integer NOT NULL,
[experience_level] text,
[skills_required] text,
[location_id] integer NOT NULL,
[no_of_openings] integer NOT NULL,
[salary_type_code] integer NOT NULL,
[start_date] date NOT NULL,
[end_date] date NOT NULL,
[search_committee] text,
[question_answers] text,
[official_id] integer NOT NULL,
[status_id] integer NOT NULL,
[created_at] DATETIME2 DEFAULT GETDATE(),
[created_by] text DEFAULT 'UNKNOWN',
CONSTRAINT job_grade_fk FOREIGN KEY (grade_id) REFERENCES job_grade(job_grade_id),
CONSTRAINT JOB_POSITION_PK PRIMARY KEY (job_position_id),,
);
```

Currently, no option to provide CONSTRAINT  with autoIncPkTable

we need the option to provide constraints with the below sample.
CONSTRAINT job_grade_fk FOREIGN KEY (grade_id) REFERENCES job_grade(job_grade_id),
 
_(job_grade_fk : Foreign key name, grade_id : Current table column, job_grade: Foreign Table, job_grade_id: column in the Foreign Table)_

CONSTRAINT JOB_POSITION_PK PRIMARY KEY (job_position_id),
  _(JOB_POSITION_PK : Primary key name, job_position_id- column name)_

**Comment by shah** [comment]
@razakpm according to ChatGPT:

> Prompt: does Microsoft SQL Server need a constraint clause in create table for auto incrementing primary keys?

> Answer: No, SQL Server doesn't need an explicit CONSTRAINT clause in the CREATE TABLE statement for auto-incrementing primary keys. The IDENTITY property can be used directly with the data type in the column definition, and the PRIMARY KEY keyword is used to specify the column as a primary key.

Have you read something else in Microsoft documentation?
I'll assume ChatGPT is correct and close this ticket but if I'm wrong please reopen it and show the evidence.
