### ISSUE TITLE
Support VARCHAR(x) domain

### ISSUE THREAD

**Issue by razakpm** [netspective-labs/sql-aide#25]
Need support of VARCHAR(x) domain
currently text domain helps , but for MSSQL,  VARCHAR(x) is the better option

**Comment by shah** [comment]
@razakpm this is pretty easy to do -- in the `string` domain's `SQL(ctx)` function check for MS SQL dialect and emit `VARCHAR(max)` instead of `TEXT`. This is the same as you've done before.

**Comment by razakpm** [comment]
@shah VARCHAR(max) needed for PostgreSQL and MSSQL. also need to pass integer from the typescript. so need your support for the implementation.

**Comment by shah** [comment]
As we discussed, for now let's force developers to use modern techniques of large text unless there's a performance or other issue. `VARCHAR(n)` should only be used sparingly these days so we'll implement it later when it's truly necessary.
