### ISSUE TITLE
Search feature in GitHub pages is not working

### ISSUE THREAD

**Issue by shah** [netspective-labs/sql-aide#41]
@ovbutt thanks to your contributions, the documentation has made it's way to GitHub pages properly but the search box appears to be broken. Here's what appears when I type in a search query:

![image](https://github.com/netspective-labs/sql-aide/assets/47497/f7ba1542-f537-45aa-8f06-eb2935250eac)

**Comment by ovbutt** [comment]
Okay I am working on it.

**Comment by ovbutt** [comment]
<img width="1790" alt="image" src="https://github.com/netspective-labs/sql-aide/assets/31251140/c4f139f8-590a-442c-b7e8-bb975466de54">
Have been working on this issue, I could see these errors in the console. On researching I came on to the conclusion that there is some issue in our app build where it misses this file in the chunk folder still trying to figure out the solution for this.

**Comment by ovbutt** [comment]
hi @shah posted a fix in this branch kindly review and approve.
https://github.com/netspective-labs/sql-aide/pull/75

**Comment by shah** [comment]
I've approved it and saw that you accidentally committed `.DS_Store` so I've removed those and added them to `.gitignore`.
