### ISSUE TITLE
Support view for MSSQL 

### ISSUE THREAD

**Issue by razakpm** [netspective-labs/sql-aide#45]
To support view in MSSQL use 'CREATE or ALTER ' instead of 'CREATE or Replace' string

**Comment by shah** [comment]
@razakpm I'm not sure what you mean - is this done or do you still need to make some SQLa `render` library changes?

**Comment by razakpm** [comment]
The task has been completed with the changes made in the [pull request] (https://github.com/netspective-labs/sql-aide/pull/46), so closing the ticket.
