### ISSUE TITLE
Data Vault tables should push down the table definition options

### ISSUE THREAD

**Issue by vinodkalpaka** [netspective-labs/sql-aide#52]
SQL Aide code for the Data Vault

const hl7Hub1 = dvts.hubTable("entity", {
  hub_entity_id: primaryKey(),
  business_key1: tcf.unique(text()),
  business_key2: tcf.unique(text()),
  ...dvts.housekeeping.columns,
  
});

Output generated

```
CREATE TABLE IF NOT EXISTS "hub_entity" (
    "hub_entity_id" TEXT PRIMARY KEY NOT NULL,
    "business_key1" TEXT /* UNIQUE COLUMN */ NOT NULL,
    "business_key2" TEXT /* UNIQUE COLUMN */ NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "provenance" TEXT NOT NULL,
    UNIQUE("business_key1"),
    UNIQUE("business_key2")
);

```
So required the composite  option for the hubTable and satelliteTable also as below:

```
CREATE TABLE hub_entity (
  hub_entity_id NOT NULL,
  business_key1 NULL,
  business_key2 NULL,
  CONSTRAINT hub_entity_pkey PRIMARY KEY (hub_id),
  CONSTRAINT hub_entity_unq UNIQUE (business_key1, business_key2)
);
```

**Comment by shah** [comment]
This appears to be done so I'm closing it. @vinodkalpaka if you still need to do some work on it please reopen.

**Comment by vinodkalpaka** [comment]
Add unique constraints to the Data Vault link tables.
