### ISSUE TITLE
add support with NVARCHAR to textEnumTable

### ISSUE THREAD

**Issue by vinodkalpaka** [netspective-labs/sql-aide#54]
When we use textEnumTable the below code 
```
export enum jobStatusContext {
  ACTIVE = "ACTIVE",
  DRAFT = "DRAFT",
  DELETED = "DELETED",
}
const jobStatusCtx = gm.textEnumTable("job_status", jobStatusContext);
```
Returns 
 ```
CREATE TABLE [job_status] (
    [code] TEXT PRIMARY KEY NOT NULL,
    [value] TEXT NOT NULL,
    [created_at] DATETIME2 DEFAULT GETDATE()
);
```
MSSQL not supporting TEXT data type for the Primary key so we need data type as NVARCHAR

MSSQL not supporting  NVARCHAR(max) also, we need to specify the predefined length like NVARCHAR(4000) 

The final output expected is 

 CREATE TABLE [job_status] (
    [code] NVARCHAR(450) PRIMARY KEY NOT NULL,
    [value] NVARCHAR(450) NOT NULL,
    [created_at] DATETIME2 DEFAULT GETDATE()
);

**Comment by shah** [comment]
Please fix this ticket with full explanation, what you're seeing now, and what you want to see. You can reopen it or handle the change yourself.

**Comment by razakpm** [comment]
This issue is fixed by adding NVARCHAR(450) support for textEnumTable in MSSQL case
