### ISSUE TITLE
Request for the support of floating point types.

### ISSUE THREAD

**Issue by avinashkurup** [netspective-labs/sql-aide#6]
Hi,
    I would like sql-aide to generate PostgreSQL schemas with support for the following data types,
- real (float4)
- double precision (float8)

as per [this list](https://www.postgresql.org/docs/14/datatype.html#DATATYPE-TABLE). Kindly look into this.

Thanks,
Avinash.

**Comment by shah** [comment]
This is done but the right dialect needs to be passed in. 

![image](https://github.com/netspective-labs/sql-aide/assets/47497/e6db2746-7d66-4b32-9296-04910fecd3a7)
