### ISSUE TITLE
Unit tests fails with  "Fatal JavaScript out of memory: Ineffective mark-compacts near heap limit " error 

### ISSUE THREAD

**Issue by razakpm** [netspective-labs/sql-aide#78]
When running unit tests in the parent directory using the "deno-test" command, an error occurs with the message "Fatal JavaScript out of memory: Ineffective mark-compacts near heap limit." This error occurs because the JavaScript heap size is not large enough to accommodate the memory requirements of the program.

Resolution Steps:
To resolve this issue, it is necessary to increase the memory limit for the JavaScript heap by using the "--v8-flags" command-line option. You can run the following command:
`deno test --v8-flags="--max-old-space-size=4096"`

Alternatively, you can set the DENO_FLAGS environment variable by adding the following line to the shell's configuration file:
`export DENO_FLAGS="--v8-flags=--max-old-space-size=4096"`

By implementing either of these approaches, the memory limit for the JavaScript heap will be increased, allowing the program to allocate sufficient memory and resolve the "Fatal JavaScript out of memory" error.
```

**Comment by shah** [comment]
@razakpm it's probably best to use the `DENO_FLAGS` env var for now; on my machines with 32GB of RAM and on CI/CD server at GitHub there are no issues so let's assume devs need to manage this on their own when they have lower RAM or similar issues.

**Comment by shah** [comment]
Added the suggested fix into CI/CD and build tasks.
