### ISSUE TITLE
Unable to access the Github Repository

### ISSUE THREAD

**Issue by Gowtham-V-CGVAK** [netspective-labs/sql-aide#79]
While trying to access the GitHub Repository using the following link: 
https://netspective-labs.github.io/sql-aide/contributors/how-to-start-contributing/%5Blink-to-github-repo%5D(https://github.com/netspective-labs/sql-aide/issues)

it shows. 404 error. Please help me to get the access.

**Comment by ovbutt** [comment]
Thanks for creating this issue @Gowtham-V-CGVAK, I am looking into it. But for issues page you can navigate to.

https://github.com/netspective-labs/sql-aide/issues

**Comment by shah** [comment]
Thanks @Gowtham-V-CGVAK for the report and @ovbutt for the fix!
