### ISSUE TITLE
autoIncPkTable Not supporting SqlNamespaceSupplier

### ISSUE THREAD

**Issue by razakpm** [netspective-labs/sql-aide#91]
Sqla not supporting the following template to create a table that includes a schema/namespace.

```
const sampSchema = gm.autoIncPkTable("samp_schema", {
  samp_schema_id: autoIncPK(),
  ...gm.housekeeping.columns,
}, { sqlNS: jobSchema });
```
code fails with the message
` "Argument of type '{ sqlNS: tp.SQLa.SchemaDefinition<"dbo", tp.SQLa.SqlEmitContext> & tp.SQLa.SqlTextLintIssuesPopulator<tp.SQLa.SqlEmitContext>; }' is not assignable to parameter of type '{ readonly constraints?:"`

**For MSSQL If we want to create a table in a different schema, we will still need to explicitly specify the schema name in the CREATE TABLE statement.** 

If we use the code provided below instead of the previous code, this feature will work.
```
const schemaSample = SQLa.tableDefinition("samp_schema", {
   samp_schema_id: autoIncPK(),
  created_at: date(),
  craeted_by: text(),
}, { sqlNS: jobSchema });
```

**Comment by shah** [comment]
This has been fixed in `v0.5.10`.
