### ISSUE TITLE
Require SERIAL auto increment field for metrics and telemetry in PostgreSQL

### ISSUE THREAD

**Issue by vinodkalpaka** [netspective-labs/sql-aide#98]
**Require SERIAL instead of INTEGER for the auto increment field for the use metrics and telemetry in PostgreSQL (v0.5.6).**

We need to generate output for metrics and telemetry with SERIAL Primary Key instead of having an INTEGER Primary Key for the auto increment field.

The generated fixture-SQL code is available here:  [_pattern/observability/mod_test.metrics-pg-fixture.sql_](https://github.com/netspective-labs/sql-aide/blob/main/pattern/observability/mod_test.metrics-pg-fixture.sql)

**Generated code snippet:**
``` 
CREATE TABLE IF NOT EXISTS "metric" (
    "metric_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" TEXT NOT NULL,
    "unit" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL
);
```
**Required code:**
```
CREATE TABLE IF NOT EXISTS "metric" (
    "metric_id" SERIAL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" TEXT NOT NULL,
    "unit" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL
);
```
As per the previous ticket, _https://github.com/netspective-labs/sql-aide/issues/56_, there is  a  support for PostgreSQL auto increment using the constant  'serialPrimaryKey'. (line 26 of https://github.com/netspective-labs/sql-aide/blob/main/pattern/observability/metrics.ts). As the telemetry and metrics patterns create tables using the  constant autoIncPrimaryKey, this will produce the output 'IDENTITY(1,1) PRIMARY KEY' for MSSQL Server and 'PRIMARY KEY AUTOINCREMENT for other databases including PostgreSQL.

Here is the code section that I were supposed to change for the PostgreSQL dialect: (line 94  of https://github.com/netspective-labs/sql-aide/blob/main/render/ddl/table/primary-key.ts) 
```
if (tmpl.isMsSqlServerDialect(ctx.sqlDialect)) {
          return `IDENTITY(1,1) PRIMARY KEY`;
        }
        return `PRIMARY KEY AUTOINCREMENT`;
      },
```
But, as the above code does not mention about the domain, only a change here for the PostgreSQL dialect, will not provide the intended result. 

So it would be better if we add the SERIAL auto-incrementing  primary key for the metrics and telemetry.

**Comment by shah** [comment]
This has been fixed in `v0.5.9`. Please see commit log for how it was accomplished.
